# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

# Default group variables
# =================

# .. contents:: Sections
#    :local:
#

# .. envvar:: target_host_name
# .. envvar:: target_host_domain
#
# Specify hostname and domain that should be set in the target image.
target_host_name: 'homevault'
target_host_domain: 'lifamilyclub.com'

# .. envvar:: target_root_password
#
# Specify root password
target_root_password: 'secret'

# .. envvar:: target_timezone
#
# Specify timezone in target host
target_timezone: 'Australia/Sydney'

# .. envvar:: target_data_root
#
# Specify folder that will be use as root of data directory
target_data_root: '/yongxin'

# .. envvar:: target_mount_device
#
# List of Disk label and mountas will be use to mount partition when booting up
# this will be setup in script/casper-bottom/12fstab
target_mount_device:
  - { label: 'data1', mountas: '{{ target_data_root }}' }
  - { label: 'data2', mountas: '{{ target_data_root }}/archive' }

# .. envvar:: target_appdata_root
#
# Specify folder that will be use as new location of application data files
# in case if you want to collect all appdata files in one
target_appdata_root: '{{ target_data_root }}/private/var'

# .. envvar:: private_overlay_root
#
# Specify the folder that will be use to mount as overlay
overylay_private_root: '{{ target_data_root }}/private'

# .. envvar:: private_overlay_default
#
# List of folders that will be overlay when booting up
overylay_private_folder: '/etc /home'

# .. envvar:: build_image_initrd
# .. envvar:: build_image_vmlinuz
# .. envvar:: build_base_image
#
# Specify file name for initrd, vmlinuz, base and overlay squashfs
build_image_initrd: 'initrd.lz'
build_image_vmlinuz: 'vmlinuz'
build_base_image: 'basefs.squashfs'
build_overlay_image: 'filesystem.squashfs'

# .. envvar:: build_image_iso
#
# Specify target iso file name
build_image_iso: 'homevault_{{ debstrap_dist }}_{{ debstrap_suite }}.iso'

# .. envvar:: build_kernel_version
#
# Specify Linux kernel version will be use in the target image.
# Available version for ubuntu
# - 4.4.0-42-generic  => trusty
# - 3.16.0-60-generic => trusty
build_kernel_version: '4.4.0-42-generic'

# .. envvar:: debstrap_dist
# .. envvar:: debstrap_arch
# .. envvar:: debstrap_suite
#
# Specify target debootstrap will be build
debstrap_dist: 'ubuntu'
debstrap_arch: 'amd64'
debstrap_suite: 'trusty'

# .. envvar:: apt_proxy
#
# Specify apt cacher / proxy link, like 'x.x.x.x:3142/'
apt_proxy:

# .. envvar:: debstrap_base_mirror
#
# Specify debootstrap mirror link
debstrap_base_mirror: '{{ apt_proxy }}us.archive.ubuntu.com'
debstrap_mirror: 'http://{{ debstrap_base_mirror }}/{{ debstrap_dist }}'

# .. envvar:: debstrap_include_packages
#
# Specify base packages that will be included when debootstrap environment.
debstrap_include_packages: 'python,python-apt'

# .. envvar:: ubuntu_repo_lists
#
# Specify apt repository for ubuntu
ubuntu_repo_lists:
  - { dest: '/etc/apt/sources.list', line: 'deb {{ debstrap_mirror }} {{ debstrap_suite }} main' }
  - { dest: '/etc/apt/sources.list.d/updates.list', line: 'deb {{ debstrap_mirror }} {{ debstrap_suite }}-updates main' }
  - { dest: '/etc/apt/sources.list.d/universe.list', line: 'deb {{ debstrap_mirror }} {{ debstrap_suite }} universe' }
  - { dest: '/etc/apt/sources.list.d/updatesuniverse.list', line: 'deb {{ debstrap_mirror }} {{ debstrap_suite }}-updates universe' }
