#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring fstab..."
FSTAB=/root/etc/fstab

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

cat > $FSTAB <<EOF
# ${UNIONFS} / ${UNIONFS} rw 0 0
tmpfs /tmp tmpfs nosuid,nodev 0 0
EOF

rm -f /root/etc/rcS.d/S*checkroot.sh

{% if target_mount_device is defined and target_mount_device %}
  {% for item in target_mount_device %}
if ls -l /dev/disk/by-label | grep {{ item.label }} > /dev/null; then
  echo "LABEL={{ item.label }}   {{ item.mountas }}        ext4    defaults  0  0" >> $FSTAB
fi
  {% endfor %}
{% endif %}

log_end_msg