# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================
# Default host variables
# =================
[build_local]
localhost                       ansible_connection=local

# chroot connection
[initrd_rootfs]
/tmp/in_target/initrd/rootfs    ansible_connection=chroot

[basefs_rootfs]
/tmp/in_target/basefs/rootfs    ansible_connection=chroot

[build_rootfs]
/tmp/in_target/build/rootfs     ansible_connection=chroot

[in_target:vars]
initrd_rootfs=/tmp/in_target/initrd/rootfs
basefs_rootfs=/tmp/in_target/basefs/rootfs
build_rootfs=/tmp/in_target/build/rootfs

build_lower_dir=/tmp/in_target/build/lower
build_upper_dir=/tmp/in_target/build/upper
build_work_dir=/tmp/in_target/build/work

build_image_root=/tmp/in_target/image

[in_target:children]
build_local
initrd_rootfs
basefs_rootfs
build_rootfs
