# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# ------------------------------------
#   HP Gen8 Management Component Pack
# ------------------------------------
install_role_name: 'hpgen8'

# .. envvar:: hpgen8_repo_key
#
# APT GPG key server and id used to sign the ansible packages.
hpgen8_repo_key:
  - 'http://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub'
  - 'http://downloads.linux.hpe.com/SDR/hpPublicKey2048.pub'
  - 'http://downloads.linux.hpe.com/SDR/hpPublicKey2048_key1.pub'
  - 'https://downloads.linux.hpe.com/SDR/hpePublicKey2048_key1.pub'

# .. envvar:: apt_proxy
#
# Specify apt cacher / proxy link, like 'x.x.x.x:3142/'
apt_proxy:

# .. envvar:: hpgen8_repository
#
# Address of the HP MgmPack APT repository.
hpgen8_repository:
  - { dest: '/etc/apt/sources.list.d/{{ install_role_name }}.list', line: 'deb http://{{ apt_proxy }}downloads.linux.hpe.com/SDR/repo/mcp/Ubuntu {{ ansible_distribution_release }}/current non-free' }

# .. envvar:: hpgen8_base_packages
#
# List of base packages to install by Ansible
# package: package will be installed
# version: package version, default is '*'
# example: - { package: 'package', version: '1.2' }
hpgen8_base_packages:
  - { package: "hp-health" }
  - { package: "hponcfg" }
  - { package: "hp-ams" }
  - { package: "ssacli" }       # replace hpssacli
  - { package: "ssaducli" }     # replace hpssaducli
  - { package: "lsof" }

# .. envvar:: hpgen8_packages
#
# List of additional packages to install by Ansible
hpgen8_packages: []

# .. envvar:: hpgen8_configuration
#
# List of configuration file will be copy to Linux base filesystems
hpgen8_configuration:
  - { name: "etc-network-interfaces.j2", dest: "/etc/network/interfaces" }
  - { name: 'network-{{ install_role_name }}.cfg.j2', dest: '/etc/network/interfaces.d/{{ install_role_name }}.cfg' }
  - { name: "etc-init.d-init-{{ install_role_name }}.sh.j2", dest: "etc/init.d/init-{{ install_role_name }}.sh", mode: "0755" }
