# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: update local and create image directory
  file:
    path: "{{ build_image_root }}/{{ item }}"
    state: directory
  with_items:
    - casper

- name: update target and remove unused files before creating image
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ build_root }}/usr/sbin/policy-rc.d"
    - "{{ build_root }}/etc/hostname"
    - "{{ build_root }}/etc/hosts"
    - "{{ build_root }}/etc/resolv.conf"
    - "{{ build_image_root }}/casper/{{ build_image_initrd }}"
    - "{{ build_image_root }}/casper/{{ build_image_vmlinuz }}"

- name: update local copy to target directory
  command: >
    cp {{ build_root }}/boot/{{ item.src }} {{ build_image_root }}/casper/{{ item.dest }}
  with_items:
    - { src: "initrd.img-{{ build_kernel_version }}", dest: "{{ build_image_initrd }}"  }
    - { src: "vmlinuz-{{ build_kernel_version }}", dest: "{{ build_image_vmlinuz }}"  }
