# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# ------------------------------------
#   Packages and installation
# ------------------------------------
install_role_name: 'hhvm'

# .. envvar:: target_host_name
# .. envvar:: target_host_domain
#
# Specify hostname and domain that should be set in the target image.
target_host_name: 'captainL'
target_host_domain: 'lifamilyclub.com'

# .. envvar:: apt_proxy
#
# Specify apt cacher / proxy link, like 'x.x.x.x:3142/'
apt_proxy:

# .. envvar:: phpfpm_repo_keyserver
# .. envvar:: phpfpm_repo_keyid
#
# APT GPG key server and id used to sign the ansible packages.
hhvm_repo_keyserver: 'keyserver.ubuntu.com'
hhvm_repo_keyid: '0x5a16e7281be7a449'

# .. envvar:: phpfpm_repository
# .. envvar:: phpfpm_v70_repository
#
# Address of the ansible APT repository.
hhvm_repository:
  - { dest: '/etc/apt/sources.list.d/{{ install_role_name }}.list', line: 'deb http://{{ apt_proxy }}dl.hhvm.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main' }
  - { dest: '/etc/apt/sources.list.d/updates.list', line: 'deb {{ debstrap_mirror }} {{ ansible_distribution_release }}-updates main' }
  - { dest: '/etc/apt/sources.list.d/updatesuniverse.list', line: 'deb {{ debstrap_mirror }} {{ ansible_distribution_release }}-updates universe' }

# .. envvar:: target_data_root
#
# Specify folder that will be use as root of user data directory
target_data_root: '/var'

# .. envvar:: target_web_root
#
# Specify folder that will be use as root of user data directory
target_web_root: '{{ target_data_root }}/public_html'

# .. envvar:: phpfpm_base_packages
#
# List of base packages to install by Ansible
# package: package will be installed
# version: package version, default is '*'
# example: - { package: 'package', version: '1.2' }
hhvm_base_packages:
  - { package: 'hhvm' }

# .. envvar:: phpfpm_packages
#
# List of additional packages to install by Ansible
# libmagickcore5-extra for libmagickcore-extra in trusty-updates
hhvm_packages:
  - { package: 'ghostscript' }          # for Ghostscript support in MediaWiki
  - { package: 'libgs-dev' }            # for Ghostscript support in MediaWiki
  - { package: 'imagemagick' }          # for image convert support in MediaWik
  - { package: 'libmagickcore-6.q16-2-extra' }  # package for libmagickcore-extra in xenial-updates
  - { package: 'ffmpeg' }               # mp4 transcode support
  - { package: 'ffmpeg2theora' }        # mp4 transcode support
  - { package: 'libav-tools' }          # mp4 transcode support

hhvm_configuration:
  - { name: 'etc-nginx-confd-default.conf.j2', dest: '/etc/nginx/conf.d/default.conf' }
  - { name: 'etc-nginx-confd-default.ini.j2', dest: '/etc/nginx/conf.d/default.ini' }
  - { name: 'etc-hhvm-server.ini.j2', dest: '/etc/hhvm/server.ini' }
  - { name: 'etc-hhvm-php.ini.j2', dest: '/etc/hhvm/php.ini' }