# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# ------------------------------------
#   Packages and installation
# ------------------------------------
install_role_name: 'nfsv4'

# .. envvar:: target_data_root
#
# Specify folder that will be use as root of user data directory
target_data_root: '/var'

# .. envvar:: nfsv4_base_packages
#
# List of base packages to install by Ansible
# package: package will be installed
# version: package version, default is '*'
# example: - { package: 'package', version: '1.2' }
nfsv4_base_packages:
  - { package: 'nfs-kernel-server', version: '*' }

# .. envvar:: nfsv4_packages
#
# List of additional packages to install by Ansible
# package: package will be installed
# version: package version, default is '*'
# example: - { package: 'package', version: '1.2' }
nfsv4_packages: []

# .. envvar:: nfsv4_configuration
#
# List of configuration file will be copy to Linux base filesystems
nfsv4_configuration:
  - { name: 'etc-exports.j2', dest: '/etc/exports' }
  - { name: 'etc-init.d-init-nfsv4.sh.j2', dest: '/etc/init.d/init-nfsv4.sh', mode: "0755" }

# .. envvar:: nfsv4_conf_share
#
# Which hash variables are used to configure [share] section samba.conf
nfsv4_conf_share:
  vmfs:
    path: '{{ target_data_root }}/vmfs'


