# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: Configure casper for removing autologin
  replace:
    dest: "/usr/share/initramfs-tools/scripts/casper-bottom/25configure_init"
    regexp: '-n "\$USERNAME"'
    replace: '-n ""'

- name: Configure casper for adding domain name
  lineinfile:
    dest: "/usr/share/initramfs-tools/scripts/casper-bottom/18hostname"
    regexp: "{{ item.regxp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regxp: '^127(.*)HOST', line: '127.0.0.1 $HOST.{{ target_host_domain }}    $HOST' }

- name: Copy custom casper scripts
  template:
    src: "{{ item }}"
    dest: "/usr/share/initramfs-tools/scripts/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items: "{{ initrd_custom_casper_script }}"
  when: initrd_custom_casper_script is defined

- name: Remove unused casper scripts
  file:
    path: "/usr/share/initramfs-tools{{ item.name }}"
    state: absent
  with_items: "{{ initrd_script_removal_list }}"
  when: initrd_script_removal_list is defined

- name: Remove unwanted casper scripts
  lineinfile: 
    dest: "/usr/share/initramfs-tools/scripts/{{ item.dest }}"
    line: "{{ item.name }}"
    state: absent
  with_items: "{{ initrd_script_removal_list }}"
  when: initrd_script_removal_list is defined

- name: Add extra modules to initramfs
  shell: "echo {{ item }} >> /etc/initramfs-tools/modules"
  with_items: 
    - squashfs

- name: Copy cleanup sciprts
  template: 
    src: "{{ playbook_dir }}/templates/{{ item.name }}"
    dest: "/tmp/{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ initrd_cleanup_script  }}"

- name: Execute cleanup sciprts
  shell: >
    /tmp/{{ item.dest }}
  with_items: "{{ initrd_cleanup_script  }}"

- name: Remove cleanup sciprts
  file:
    path: "/tmp/{{ item.dest }}"
    state: absent
  with_items: "{{ initrd_cleanup_script  }}"

- name: Update initramfs with new modules and drivers
  shell: >
    update-initramfs -u

- name: Rebuild initramfs image with version {{ build_kernel_version }}
  shell: >
    mkinitramfs -v -o
    /boot/initrd.img-{{ build_kernel_version }} {{ build_kernel_version }}