# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: update target and add {{ install_role_name }} repository key
  apt_key: 
    keyserver: "{{ docker_repo_keyserver }}"
    id: "{{ docker_repo_keyid }}"
    state: present

- name: update target and add {{ install_role_name }} repository list
  lineinfile: 
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
    create: yes
    state: present
  with_items: "{{ docker_repository }}"

- name: update target and verify APT is pulling from right repository
  command: >
    apt-cache policy docker-engine

- name: update target and install required {{ install_role_name }} packages
  apt: 
    name: "{{ item.package }}={{ item.version|default('*') }}"
    install_recommends: no
    update_cache: yes
  register: install_pkgs
  until: install_pkgs|success
  retries: 2
  delay: 5
  with_flattened:
    - "{{ docker_base_packages }}"
    - "{{ docker_packages }}"

- name: update target and add users to {{ install_role_name }} group
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: yes
  with_items: "{{ docker_admins }}"
  when: docker_admins is defined

- name: update target and remove {{ install_role_name }} repository list
  file: 
    path: "{{ item.dest }}"
    state: absent
  with_flattened:
    - "{{ docker_repository }}"