# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: check if pip is already install
  command: "pip --version"
  ignore_errors: true
  changed_when: false
  check_mode: no
  register: pip_installed

- name: add {{ install_role_name }} repository key
  apt_key: 
    keyserver: "{{ docker_repo_keyserver }}"
    id: "{{ docker_repo_keyid }}"
    state: present

- name: add {{ install_role_name }} repository list
  lineinfile: 
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
    create: yes
    state: present
  with_items: "{{ docker_repository }}"

- name: verify APT is pulling from right repository
  command: >
    apt-cache policy docker-engine

- name: install required {{ install_role_name }} packages (apt)
  apt: 
    name: "{{ item.package }}={{ item.version|default('*') }}"
    install_recommends: no
    update_cache: yes
  register: install_pkgs
  until: install_pkgs|success
  retries: 2
  delay: 5
  with_flattened:
    - "{{ docker_base_packages }}"
    - "{{ docker_packages }}"

- name: install required {{ install_role_name }} packages (pip)
  pip: 
    name: "{{ item.package }}"
  with_items: "{{ docker_pip_packages }}"
  when: pip_installed.rc == 0

- name: add users to {{ install_role_name }} group
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: yes
  with_items: "{{ docker_admins }}"
  when: docker_admins is defined

- name: remove {{ install_role_name }} repository list
  file: 
    path: "{{ item.dest }}"
    state: absent
  with_flattened:
    - "{{ docker_repository }}"

- name: install {{ install_role_name }} compose from github
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/bin/docker-compose
    mode: 0755
  when: pip_installed.rc != 0