# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# ------------------------------------
#   Packages and installation
# ------------------------------------
install_role_name: 'phpfpm'

# .. envvar:: target_host_name
# .. envvar:: target_host_domain
#
# Specify hostname and domain that should be set in the target image.
target_host_name: 'captainL'
target_host_domain: 'lifamilyclub.com'

# .. envvar:: apt_proxy
#
# Specify apt cacher / proxy link, like 'x.x.x.x:3142/'
apt_proxy:

phpfpm_version: '7.0'

# .. envvar:: phpfpm_repo_keyserver
# .. envvar:: phpfpm_repo_keyid
#
# APT GPG key server and id used to sign the ansible packages.
phpfpm_repo_keyserver: 'keyserver.ubuntu.com'
phpfpm_repo_keyid: 'E5267A6C'

# .. envvar:: phpfpm_repository
# .. envvar:: phpfpm_v70_repository
#
# Address of the ansible APT repository.
phpfpm_repository:
  - { dest: '/etc/apt/sources.list.d/{{ install_role_name }}.list', line: 'deb http://{{ apt_proxy }}ppa.launchpad.net/ondrej/php/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main' }
  - { dest: '/etc/apt/sources.list.d/updates.list', line: 'deb {{ debstrap_mirror }} {{ ansible_distribution_release }}-updates main' }
  - { dest: '/etc/apt/sources.list.d/updatesuniverse.list', line: 'deb {{ debstrap_mirror }} {{ ansible_distribution_release }}-updates universe' }

# .. envvar:: target_data_root
#
# Specify folder that will be use as root of user data directory
target_data_root: '/var'

# .. envvar:: target_web_root
#
# Specify folder that will be use as root of user data directory
target_web_root: '{{ target_data_root }}/public_html'

# .. envvar:: phpfpm_base_packages
#
# List of base packages to install by Ansible
# package: package will be installed
# version: package version, default is '*'
# example: - { package: 'package', version: '1.2' }
phpfpm_base_packages:
  - { package: 'php{{ phpfpm_version }}' }
  - { package: 'php{{ phpfpm_version }}-cli' }
  - { package: 'php{{ phpfpm_version }}-common' }
  - { package: 'php{{ phpfpm_version }}-fpm' }

# .. envvar:: phpfpm_packages
#
# List of additional packages to install by Ansible
# libmagickcore5-extra for libmagickcore-extra in trusty-updates
phpfpm_packages:
  - { package: 'ghostscript' }                  # ghostScript support
  - { package: 'libgs-dev' }                    # ghostScript support
  - { package: 'imagemagick' }                  # ghostScript support
  - { package: 'poppler-utils' }                # pdf utilities / support
  - { package: 'libmagickcore-6.q16-2-extra' }  # package for libmagickcore-extra in xenial-updates
# - { package: 'ffmpeg' }                       # mp4 transcode support
# - { package: 'ffmpeg2theora' }                # mp4 transcode support
# - { package: 'libav-tools' }                  # mp4 transcode support
  - { package: 'php-apcu' }
  - { package: 'php-pear' }
  - { package: 'php-imagick' }
  - { package: 'php{{ phpfpm_version }}-curl' }
  - { package: 'php{{ phpfpm_version }}-gd' }
  - { package: 'php{{ phpfpm_version }}-imap' }
  - { package: 'php{{ phpfpm_version }}-intl' }
  - { package: 'php{{ phpfpm_version }}-ldap' }
  - { package: 'php{{ phpfpm_version }}-json' }
  - { package: 'php{{ phpfpm_version }}-mbstring' }
  - { package: 'php{{ phpfpm_version }}-mcrypt' }
  - { package: 'php{{ phpfpm_version }}-mysql' }
  - { package: 'php{{ phpfpm_version }}-opcache' }
  - { package: 'php{{ phpfpm_version }}-readline' }
  - { package: 'php{{ phpfpm_version }}-pgsql' }
  - { package: 'php{{ phpfpm_version }}-tidy' }
  - { package: 'php{{ phpfpm_version }}-xml' }
  - { package: 'php{{ phpfpm_version }}-xmlrpc' }

phpfpm_configuration:
  - { name: 'etc-nginx-confd-default.conf.j2', dest: '/etc/nginx/conf.d/default.conf' }
  - { name: 'etc-nginx-confd-default.ini.j2', dest: '/etc/nginx/conf.d/default.ini' }
