# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: copy {{ install_role_name }} configure files
  template:
    src: "{{ item.name }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ webmin_configuration }}"

- name: remove {{ install_role_name }} modules configuration
  file:
    path: "{{ debian_config_root }}/{{ item }}"
    state: absent
  with_items: "{{ webmin_module_removal }}"

- name: remove {{ install_role_name }} modules
  file: 
    path: "{{ debian_module_root }}/{{ item }}"
    state: absent
  with_items: "{{ webmin_module_removal }}"

- name: cleanup {{ install_role_name }} installation
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/webmin-setup.out"
    - "/var/webmin"

- name: update webmin root password
  command: >
    /usr/share/webmin/changepass.pl /etc/webmin root {{ target_root_password }}
  when: target_root_password is defined

- name: remove {{ install_role_name }} services from booting
  command: update-rc.d -f {{ item }} remove
  with_items:
    - webmin

- name: update target and include init-functions into rc.local
  lineinfile:
    dest: "/etc/rc.local"
    line: ". /lib/lsb/init-functions"
    insertafter: "# By default this script does nothing."
    owner: root
    group: root
    mode: 0755
    state: present
    create: yes

- name: update target and start {{ install_role_name }} from rc.local
  blockinfile:
    dest: "/etc/rc.local"
    insertbefore: "exit 0"
    marker: "# {mark} MANAGED {{ install_role_name }} BLOCK"
    owner: root
    group: root
    mode: 0755
    state: present
    create: yes 
    block: |
      /etc/init.d/init-{{ install_role_name }}.sh
      log_begin_msg "Starting {{ install_role_name }} daemon"
      if [ $(ps -ef | grep -c webmin) != 1 ]; then
        service webmin restart > /dev/null
      else
        service webmin start > /dev/null
      fi
      log_end_msg 0