# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: update local and create image directory
  file:
    path: "{{ build_image_root }}/{{ item }}"
    state: directory
  with_items:
    - casper
    - isolinux
    - syslinux    

- name: update local and unmount rootfs in build directory
  mount: 
    name: "{{ build_root }}/{{ item }}"
    src: none
    fstype: none
    state: unmounted
  with_items:
    - proc
    - dev
    - dev/pts

- name: update local and download hardware detection tool (PCIID)
  get_url:
    url: "{{ pciid_base_mirror }}"
    dest: "{{ build_image_root }}/syslinux/pci.ids"
    force: yes

- name: update local and download base syslinux packages
  command: cp "{{ build_root }}/usr/lib/{{ item }}" "{{ build_image_root }}/syslinux"
  with_flattened:
    - "{{ syslinux_base_packages }}"

- name: update local and download syslinux packages
  command: cp "{{ build_root }}/{{ item }}" "{{ build_image_root }}/syslinux"
  with_flattened:
    - "{{ syslinux_packages }}"

- name: update local and copy syslinux menu
  template:
    src: "{{ item.name }}"
    dest: "{{ build_image_root }}/{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ syslinux_configuration }}"

- name: update target and remove unused files before creating image
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ build_root }}/usr/sbin/policy-rc.d"
    - "{{ build_root }}/etc/hostname"
    - "{{ build_root }}/etc/hosts"
    - "{{ build_root }}/etc/resolv.conf"
    - "/tmp/{{ build_image_iso }}"

- name: update target and exclude base squashfs from image
  command:  mv "{{ build_image_root }}/casper/{{ build_base_image }}" /tmp

- name: generate iso image {{ build_image_iso }} in /tmp
  command: >
    genisoimage -V {{ target_host_name }} -quiet -l -r -J -input-charset utf-8 \
    -o /tmp/{{ build_image_iso }} \
    -b syslinux/isolinux.bin -c syslinux/boot.cat \
    -no-emul-boot -boot-load-size 4 -boot-info-table {{ build_image_root }}