# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: update target and copy {{ install_role_name }} configure files
  template:
    src: "{{ item.name }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ phpfpm_configuration }}"
  when: phpfpm_version == "5.6"

- name: update target and copy {{ install_role_name }} configure files
  template:
    src: "{{ item.name }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ phpfpm_v70_configuration }}"
  when: phpfpm_version == "7.0"

- name: update target and remove {{ install_role_name }} services from booting
  command: update-rc.d -f {{ item }} remove
  with_items:
    - php5-fpm
  when: ansible_os_family == "Debian" and phpfpm_version == "5.6"

- name: update target and remove {{ install_role_name }} services from booting
  command: update-rc.d -f {{ item }} remove
  with_items:
    - php7.0-fpm
  when: ansible_os_family == "Debian" and phpfpm_version == "7.0"

- name: update target and remove {{ install_role_name }} services from booting
  lineinfile:
    dest: "{{ item }}"
    line: "manual"
    owner: root
    group: root
    mode: 0644
    state: present
    create: yes
  with_items:
    - /etc/init/php5-fpm.override
  when: ansible_os_family == "Debian" and phpfpm_version == "5.6"

- name: update target and remove {{ install_role_name }} from upstart
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/init/php5-fpm.conf
  when: ansible_os_family == "Debian" and phpfpm_version == "5.6"

- name: update target and remove {{ install_role_name }} services from booting
  lineinfile:
    dest: "{{ item }}"
    line: "manual"
    owner: root
    group: root
    mode: 0644
    state: present
    create: yes
  with_items:
    - /etc/init/php7.0-fpm.override
  when: ansible_os_family == "Debian" and phpfpm_version == "7.0"

- name: update target and enable root user for {{ install_role_name }} services
  lineinfile:
    dest: '{{ item }}'
    regexp: '^DAEMON_ARGS.*'
    line: 'DAEMON_ARGS="--daemonize --allow-to-run-as-root --fpm-config $CONFFILE"'
    state: present
  with_items:
    - /etc/init.d/php5-fpm
  when: ansible_os_family == "Debian" and phpfpm_version == "5.6"

- name: update target and enable root user for {{ install_role_name }} services
  lineinfile:
    dest: '{{ item }}'
    regexp: '^DAEMON_ARGS.*'
    line: 'DAEMON_ARGS="--daemonize --allow-to-run-as-root --fpm-config $CONFFILE"'
    state: present
  with_items:
    - /etc/init.d/php7.0-fpm
  when: ansible_os_family == "Debian" and phpfpm_version == "7.0"

- name: update target and change {{ install_role_name }} php-fpm configuration
  lineinfile:
    dest: '/etc/php/7.0/fpm/php-fpm.conf'
    regexp: "{{ item.regxp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regxp: '^pid.*', line: 'pid = /run/php7.0-fpm.pid' }
  when: ansible_os_family == "Debian" and phpfpm_version == "7.0"

- name: update target and change {{ install_role_name }} php-fpm configuration
  lineinfile:
    dest: '/etc/php5/fpm/pool.d/www.conf'
    regexp: "{{ item.regxp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regxp: '^user.*', line: 'user = root' }
    - { regxp: '^group.*', line: 'group = root' }
    - { regxp: '^(.?)listen =.*', line: 'listen = 9000' }
    - { regxp: '^(.?)listen.owner.*', line: 'listen.owner = root' }
    - { regxp: '^(.?)listen.group.*', line: 'listen.group = root' }
    - { regxp: '^(.?)listen.mode.*', line: 'listen.mode = 0660' }
    - { regxp: '^(.?)listen.allowed_clients.*', line: 'listen.allowed_clients = 127.0.0.1' }
    - { regxp: '^;security.limit_extensions.*', line: 'security.limit_extensions = .php .php3 .php4 .php5' }
  when: ansible_os_family == "Debian" and phpfpm_version == "5.6"

- name: update target and change {{ install_role_name }} php-fpm configuration
  lineinfile:
    dest: '/etc/php/7.0/fpm/pool.d/www.conf'
    regexp: "{{ item.regxp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regxp: '^user.*', line: 'user = root' }
    - { regxp: '^group.*', line: 'group = root' }
    - { regxp: '^(.?)listen =.*', line: 'listen = 9000' }
    - { regxp: '^(.?)listen.owner.*', line: 'listen.owner = root' }
    - { regxp: '^(.?)listen.group.*', line: 'listen.group = root' }
    - { regxp: '^(.?)listen.mode.*', line: 'listen.mode = 0660' }
    - { regxp: '^(.?)listen.allowed_clients.*', line: 'listen.allowed_clients = 127.0.0.1' }
    - { regxp: '^;security.limit_extensions.*', line: 'security.limit_extensions = .php .php3 .php4 .php5' }
  when: ansible_os_family == "Debian" and phpfpm_version == "7.0"

- name: update target and change {{ install_role_name }} php configuration
  lineinfile:
    dest: '/etc/php5/fpm/php.ini'
    regexp: "{{ item.regxp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regxp: '^post_max_size.*', line: 'post_max_size = 768M' }
    - { regxp: '^upload_max_filesize.*', line: 'upload_max_filesize = 768M' }
    - { regxp: '^;opcache.enable.*', line: 'opcache.enable = 1' }
    - { regxp: '^;opcache.enable_cli.*', line: 'opcache.enable_cli = 1' }
    - { regxp: '^;opcache.memory_consumption.*', line: 'opcache.;opcache.memory_consumption = 64' }
    - { regxp: '^;opcache.interned_strings_buffer.*', line: 'opcache.interned_strings_buffer = 8' }
    - { regxp: '^;opcache.max_accelerated_files.*', line: 'opcache.max_accelerated_files = 8000' }
    - { regxp: '^;opcache.max_wasted_percentage.*', line: 'opcache.max_wasted_percentage = 5' }
    - { regxp: '^;opcache.validate_timestamps.*', line: 'opcache.validate_timestamps = 1' }
    - { regxp: '^;opcache.revalidate_freq.*', line: 'opcache.revalidate_freq = 60' }
    - { regxp: '^;opcache.fast_shutdown.*', line: 'opcache.fast_shutdown = 1' }
  when: ansible_os_family == "Debian" and phpfpm_version == "5.6"

- name: update target and change {{ install_role_name }} php configuration
  lineinfile:
    dest: '/etc/php/7.0/fpm/php.ini'
    regexp: "{{ item.regxp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regxp: '^post_max_size.*', line: 'post_max_size = 768M' }
    - { regxp: '^upload_max_filesize.*', line: 'upload_max_filesize = 768M' }
  when: ansible_os_family == "Debian" and phpfpm_version == "7.0"

- name: update target and include init-functions into rc.local
  lineinfile:
    dest: "/etc/rc.local"
    line: ". /lib/lsb/init-functions"
    insertafter: "# By default this script does nothing."
    owner: root
    group: root
    mode: 0755
    state: present
    create: yes

- name: update target and start {{ install_role_name }} from rc.local
  blockinfile:
    dest: "/etc/rc.local"
    insertbefore: "exit 0"
    marker: "# {mark} MANAGED {{ install_role_name }} BLOCK"
    owner: root
    group: root
    mode: 0755
    state: present
    create: yes 
    block: |
      log_begin_msg "Starting {{ install_role_name }} daemon"
      if [ $(ps -ef | grep -c php-fpm) != 1 ]; then
        /etc/init.d/php5-fpm restart > /dev/null
      else
        /etc/init.d/php5-fpm start > /dev/null
      fi
      log_end_msg 0
  when: ansible_os_family == "Debian" and phpfpm_version == "5.6"

- name: update target and start {{ install_role_name }} from rc.local
  blockinfile:
    dest: "/etc/rc.local"
    insertbefore: "exit 0"
    marker: "# {mark} MANAGED {{ install_role_name }} BLOCK"
    owner: root
    group: root
    mode: 0755
    state: present
    create: yes 
    block: |
      log_begin_msg "Starting {{ install_role_name }} daemon"
      if [ $(ps -ef | grep -c php-fpm) != 1 ]; then
        /etc/init.d/php7.0-fpm restart > /dev/null
      else
        /etc/init.d/php7.0-fpm start > /dev/null
      fi
      log_end_msg 0
  when: ansible_os_family == "Debian" and phpfpm_version == "7.0"