# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: mount overlay with read-only base image in build directory
  mount:
    name: "{{ build_rootfs }}"
    src: overlay
    fstype: overlay
    opts: "rw,lowerdir={{ build_lower_dir }},upperdir={{ build_upper_dir }},workdir={{ build_work_dir }}"
    state: mounted

- name: update dpkg policy to stop bg processes when installing
  blockinfile:
    dest: "{{ build_root }}/usr/sbin/policy-rc.d"
    owner: root
    group: root
    mode: 0755
    create: yes
    block: "#!/bin/sh\n
           exit 101"

- name: update repository list to rootfs
  lineinfile:
    dest: "{{ build_root }}/{{ item.dest }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items: "{{ ubuntu_repo_lists }}"
  when: debstrap_dist == "ubuntu"

- name: update repository list to rootfs
  lineinfile:
    dest: "{{ build_root }}/{{ item.dest }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items: "{{ debian_repo_lists }}"
  when: debstrap_dist == "debian"

- name: bind mount to chroot environment
  mount:
    name: "{{ build_root }}/{{ item }}"
    src: "/{{ item }}"
    fstype: none
    opts: "bind"
    state: mounted
  with_items:
    - proc
    - dev