# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: update target and set to stop bg processes when installing
  blockinfile:
    dest: "{{ build_root }}/usr/sbin/policy-rc.d"
    owner: root
    group: root
    mode: 0755
    create: yes
    block: "#!/bin/sh\n
           exit 101"

- name: update target and update repository list
  lineinfile:
    dest: "{{ build_root }}/{{ item.dest }}"
    line: "{{ item.line }}"
    state: absent
    create: yes
  with_items:
    - { dest: '/etc/apt/sources.list', line: 'deb http://au.archive.ubuntu.com/ubuntu/ {{ debstrap_suite }} main' }
    - { dest: '/etc/apt/sources.list.d/universe.list', line: 'deb http://au.archive.ubuntu.com/ubuntu/ {{ debstrap_suite }} universe' }

- name: update target and copy repository list
  lineinfile:
    dest: "{{ build_root }}/{{ item.dest }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items: "{{ ubuntu_repo_lists }}"

- name: bind mount to chroot environment
  mount:
    name: "{{ build_root }}/{{ item }}"
    src: "/{{ item }}"
    fstype: none
    opts: "bind"
    state: mounted
  with_items:
    - proc
    - dev
