# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: install build dependencies
  apt: 
    name: "{{ item }}"
    state: present
    install_recommends: no
    update_cache: yes
  register: install_pkgs
  until: install_pkgs|success
  retries: 2
  delay: 5
  with_items:
    - debootstrap

- name: check debootstrap version
  command: dpkg-query -W -f='${Version}' debootstrap
  register: deb_version

- name: download latest version of debootstrap
  get_url:
    url: "http://{{ debstrap_base_mirror }}/ubuntu/pool/main/d/debootstrap/debootstrap_{{ debstrap_version }}_all.deb"
    dest: "/tmp/debootstrap_{{ debstrap_version }}_all.deb"
  when: deb_version.stdout != debstrap_version

- name: upgrade debootstrap to {{ debstrap_version }}
  apt:
    deb: "/tmp/debootstrap_{{ debstrap_version }}_all.deb"
  when: deb_version.stdout != debstrap_version

- name: remove debootstrap package
  file:
    path: "/tmp/debootstrap_{{ debstrap_version }}_all.deb"
    state: absent
  when: deb_version.stdout != debstrap_version
