# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  pre_tasks:
    - include: tasks/unmount_rootfs.yml
    - include: tasks/mount_rootfs.yml
  roles:
    - ../basefs/pre-build

- hosts: build_rootfs
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../basefs/build-basefs
    - ../services/openssh
    #- ../services/openldap          # uncommit the line to enable this service
    - ../services/samba             # commit the line to disable this service
    - ../services/nfsv4             # commit the line to disable this service
    - ../services/ansible           # commit the line to disable this service
    - ../services/aptcacher         # commit the line to disable this service
    - ../services/git               # commit the line to disable this service
    - ../services/docker            # commit the line to disable this service
    - ../services/nginx             # commit the line to disable this service
    - ../services/phpfpm            # commit the line to disable this service
    - ../services/nodejs            # commit the line to disable this service
    - ../services/mariadb10         # commit the line to disable this service
  post_tasks:
    - include: tasks/cleanup_rootfs_debian.yml

- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../basefs/post-build
  post_tasks:
    - include: tasks/unmount_rootfs.yml
