# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  pre_tasks:
    - include: tasks/unmount_rootfs.yml
    - include: tasks/mount_rootfs.yml
  roles:
    - ../basefs/pre-build

- hosts: build_rootfs
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../basefs/build-basefs
    - ../services/openssh
    - ../services/samba
    - ../services/nfsv4
    - ../services/git
    - ../services/ansible
    - ../services/docker
    - ../services/aria2
    - ../services/nodejs
    - ../hardware/vmtools           # VMware tools and drivers
    - ../hardware/hpgen8            # HP Gen8 management Pack
    - ../services/nginx
    - ../services/phpfpm7
  post_tasks:
    - include: tasks/cleanup_rootfs_debian.yml

- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../basefs/post-build
  post_tasks:
    - include: tasks/unmount_rootfs.yml
