# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  pre_tasks:
    - import_tasks: tasks/unmount_rootfs.yml
    - import_tasks: tasks/unmount_overlay.yml
    - import_tasks: tasks/mount_overlay.yml
  roles:
    - ../imgbuild/pre-build

- hosts: build_rootfs
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../imgbuild/build-image

- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../imgbuild/post-build
  post_tasks:
    - import_tasks: tasks/unmount_overlay.yml
