# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  pre_tasks:
    - include: tasks/unmount_rootfs.yml
    - include: tasks/unmount_overlay.yml
    - include: tasks/mount_overlay.yml
  roles:
    - ../overlayfs/pre-build

- hosts: build_rootfs
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../services/webmin            # commit the line to disable this service
    - ../hardware/vmtools           # VMware tools and drivers
    - ../hardware/hpgen8            # HP Gen8 management Pack
    #- ../services/postoffice        # uncommit the line to enable this service
    #- ../services/java8             # uncommit the line to enable this service
  post_tasks:
    - include: tasks/cleanup_rootfs_debian.yml

- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../overlayfs/post-build
  post_tasks:
    - include: tasks/unmount_overlay.yml
