# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  pre_tasks:
    - include: tasks/unmount_rootfs.yml
    - include: tasks/unmount_overlay.yml
    - include: tasks/mount_overlay.yml
  roles:
    - ../overlayfs/pre-build

- hosts: build_rootfs
  vars_files:
    - ../../{{ config_file }}
  roles:
    #- ../services/openssh         # basesystems and installed in basefs playbook
    #- ../services/openldap        # basesystems and installed in basefs playbook
    #- ../services/samba           # basesystems and installed in basefs playbook
    #- ../services/nfsv4           # basesystems and installed in basefs playbook
    #- ../services/ansible         # basesystems and installed in basefs playbook
    #- ../services/git             # basesystems and installed in basefs playbook
    #- ../services/docker          # basesystems and installed in basefs playbook
    #- ../services/nginx           # basesystems and installed in basefs playbook
    #- ../services/phpfpm          # basesystems and installed in basefs playbook
    #- ../services/nodejs          # basesystems and installed in basefs playbook
    #- ../services/mariadb10       # basesystems and installed in basefs playbook
    - ../services/aptcacher
    - ../services/webmin
    #- ../services/java8           # removed from basefs playbook due to huge space required.
  post_tasks:
    - include: tasks/cleanup_rootfs_debian.yml

- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../overlayfs/post-build
  post_tasks:
    - include: tasks/unmount_overlay.yml
