# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: environment check - base squashfs image
  stat:
    path: "{{ build_image_root }}/casper/{{ build_base_image }}"
  register: squashfs_exist

- fail:
    msg: "Whoops! base squashfs image does not exist"
  when: squashfs_exist.stat.exists == False

- name: update local and create overlay directories
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - "{{ build_rootfs }}"
    - "{{ build_lower_dir }}"
    - "{{ build_upper_dir }}"
    - "{{ build_work_dir }}"

- name: mount read-only base image in build directory
  mount:
    name: "{{ build_lower_dir }}"
    src: "{{ build_image_root }}/casper/{{ build_base_image }}"
    fstype: squashfs
    state: mounted
    opts: "loop"

- name: mount overlay with read-only base image in build directory
  mount:
    name: "{{ build_rootfs }}"
    src: overlay
    fstype: overlay
    opts: "rw,lowerdir={{ build_lower_dir }},upperdir={{ build_upper_dir }},workdir={{ build_work_dir }}"
    state: mounted