# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: un-mount rootfs in build directory {{ build_root }}
  mount: 
    name: "{{ build_root }}/{{ item }}"
    src: none
    fstype: none
    state: unmounted
  with_items:
    - dev/pts
    - dev
    - proc

- name: un-mount if build directory {{ build_root }} is mounted
  mount: 
    name: "{{ build_root }}"
    src: tmpfs
    fstype: tmpfs
    state: unmounted

- name: remove build directory {{ build_root }}
  file: 
    path: "{{ build_root }}"
    state: absent
