# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# .. envvar:: target_root_password
#
# Specify root password
target_root_password: 'secret'

# .. envvar:: target_timezone
#
# Specify timezone in target host
target_timezone: 'Australia/Sydney'

# .. envvar:: private_overlay_root
#
# Specify the folder that will be use to mount as overlay
overylay_private_root: '/yongxin/private'

# .. envvar:: private_overlay_default
#
# List of folders that will be overlay when booting up
overylay_private_folder: '/etc /home /root'

# .. envvar:: basefs_configuration
#
# List of configuration file will be copy to Linux base filesystems
basefs_configuration:
    - { name: "interfaces.j2", dest: "/etc/network/interfaces" }
    - { name: "vmware.cfg.j2", dest: "/etc/network/interfaces.d/vmware.cfg" }

# .. envvar:: uninstall_build_kernel
#
# Set below param to yes if you don't want kernel modules in the Linux base filesystems
uninstall_build_kernel: 'no'

# .. envvar:: basefs_init_script
#
# List of scripts will be copy and executed when system booting up
basefs_init_script:
  - { name: "etc-init.d-mountall-overlay-private.j2", dest: "mountall-overlay-private", mode: '0755' }

# .. envvar:: persistent_files
#
# List of files will be remain after cleaning up kernel and base filesystems
persistent_files:
  - '/lib/modules/{{ build_kernel_version }}/modules.dep.bin'
  - '/lib/modules/{{ build_kernel_version }}/kernel/fs/nls/nls_iso8859-1.ko'