# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# .. envvar:: target_root_password
#
# Specify root password
target_root_password: 'secret'

# .. envvar:: target_timezone
#
# Specify timezone in target host
target_timezone: 'Australia/Sydney'

# .. envvar:: target_ntpserver
#
# Specify ntp server in target host
target_ntpserver: 'au.pool.ntp.org'

# .. envvar:: target_data_root
#
# Specify folder that will be use as root of user data directory
target_data_root: '/var'

# .. envvar:: private_overlay_root
#
# Specify the folder that will be use to mount as overlay
overylay_private_root: '{{ target_data_root }}/private'

# .. envvar:: basefs_configuration
#
# List of configuration file will be copy to Linux base filesystems
basefs_configuration:
    - { name: "etc-network-interfaces.j2", dest: "/etc/network/interfaces" }

# .. envvar:: uninstall_build_kernel
#
# Set below param to True if you don't want kernel modules in the Linux base filesystems
# uninstall_build_kernel: False

# .. envvar:: basefs_init_script
#
# List of scripts will be copy and executed when system booting up
basefs_init_script:
  - { name: "etc-init.d-mount-overlayfs.j2", dest: "/etc/init.d/mount-overlayfs", mode: "0755" }
  - { name: "lib-systemd-system-overlayfs.service.j2", dest: "/lib/systemd/system/overlayfs.service", mode: "0644" }
