# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# .. envvar:: target_data_root
#
# Specify folder that will be use as root of user data directory
target_data_root: '/var'

# .. envvar:: target_mount_device
#
# List of Disk label and mountas will be use to mount partition when booting up
# this will be setup in script/casper-bottom/12fstab
target_mount_device:
  - { label: 'data1', mountas: '{{ target_data_root }}' }
  - { label: 'data2', mountas: '{{ target_data_root }}/archive' }

# .. envvar:: target_host_domain
#
# Specify hostname and domain that should be set in the target image.
target_host_domain: 'lifamilylife.com'

# .. envvar:: initrd_custom_casper_script
#
# List of custom casper sciprt will be copy into target image
initrd_custom_casper_script:
  - casper-bottom/12fstab

# .. envvar:: initrd_script_removal_list
#
# List of casper sciprt will be remove
initrd_script_removal_list:
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/25adduser" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/30accessibility" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/31disable_update_notifier" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/32disable_hibernation" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/33enable_apport_crashes" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/34disable_kde_services" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/36disable_trackerd" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/48kubuntu_disable_restart_notifications" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/49kubuntu_mobile_session" }
  - { dest: "casper-bottom/ORDER", name: "/scripts/casper-bottom/50ubiquity-bluetooth-agent" }

# .. envvar:: initrd_cleanup_script
#
# List of sciprt will be execute in initrd rootfs
initrd_cleanup_script:
  - { name: "cleanup_rootfs_kernel.sh.j2", dest: "cleanup_rootfs_kernel.sh", mode: '0755' }