# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: create {{ install_role_name }} sharing directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0644
  with_flattened:
    - "/etc/nginx/conf.d"
    - "/etc/nginx/conf-available"
    - "/etc/nginx/httpd-enabled"
    - "/etc/nginx/https-enabled"

- name: copy {{ install_role_name }} configure files
  template:
    src: "{{ item.name }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ nginx_configuration }}"

- name: remove {{ install_role_name }} services from booting
  command: update-rc.d -f {{ item }} remove
  with_items:
    - nginx
  when: ansible_lsb.major_release|int < 15

- name: include init-functions into rc.local
  lineinfile:
    dest: "/etc/rc.local"
    line: ". /lib/lsb/init-functions"
    insertafter: "# By default this script does nothing."
    owner: root
    group: root
    mode: 0755
    state: present
    create: yes
  when: ansible_lsb.major_release|int < 15

- name: start {{ install_role_name }} from rc.local
  blockinfile:
    dest: "/etc/rc.local"
    insertbefore: "exit 0"
    marker: "# {mark} MANAGED {{ install_role_name }} BLOCK"
    owner: root
    group: root
    mode: 0755
    state: present
    create: yes 
    block: |
      /etc/init.d/init-{{ install_role_name }}.sh
      log_begin_msg "Starting {{ install_role_name }} daemon"
      if [ $(ps -ef | grep -c nginx) != 1 ]; then
        service nginx restart > /dev/null
      else
        service nginx start > /dev/null
      fi
      log_end_msg 0
  when: ansible_lsb.major_release|int < 15

- name: Check {{ install_role_name }} service file (systemd)
  stat:
    path: "/lib/systemd/system/docker.service"
  register: service_file

- name: configure {{ install_role_name }} service (systemd)
  lineinfile:
    dest: "/lib/systemd/system/docker.service"
    line: 'ExecStartPre=/etc/init.d/init-{{ install_role_name }}.sh'
    insertbefore: "^ExecStart.*"
    state: present
  when: service_file.stat.exists == True
