# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: encrypt password hash for root user
  command: >
    mkpasswd --method=sha-512 {{ target_root_password }}
  register: root_password_hash

- name: Set root password
  user:
    name: root
    password: "{{ root_password_hash.stdout }}"

- name: Set locale to default profile
  lineinfile:
    dest: "/etc/profile.d/setenv.sh"
    line: "{{ item }}"
    create: yes
    state: present
    mode: 0755
  with_items:
    - "export LC_ALL=C"
    - "export DEBIAN_FRONTEND=noninteractive"

- name: Create folder interface.d
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: 0755

- name: Setup network interface
  template:
    src: "{{ item.name }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ basefs_configuration }}"

- name: Change network waiting time for Ubuntu Trusty
  replace:
    dest: "/etc/init/failsafe.conf"
    regexp: "[245][039]$"
    replace: "3"
  when: ansible_lsb.major_release|int < 15

- name: Update NTP servers pool
  lineinfile:
    dest: "/etc/ntp.conf"
    regexp: "{{ item.regxp }}"
    line: "{{ item.line }}"
    create: yes
    state: present
    mode: 0644
  with_items:
    - { regxp: '^server 0.*', line: 'server 0.{{ target_ntpserver }}' }
    - { regxp: '^server 1.*', line: 'server 1.{{ target_ntpserver }}' }
    - { regxp: '^server 2.*', line: 'server 2.{{ target_ntpserver }}' }
    - { regxp: '^server 3.*', line: 'server 3.{{ target_ntpserver }}' }
    - { regxp: '^pool 0.*', line: 'server 0.{{ target_ntpserver }}' }
    - { regxp: '^pool 1.*', line: 'server 1.{{ target_ntpserver }}' }
    - { regxp: '^pool 2.*', line: 'server 2.{{ target_ntpserver }}' }
    - { regxp: '^pool 3.*', line: 'server 3.{{ target_ntpserver }}' }

- name: Copy init.d script
  template:
    src: "{{ item.name }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ basefs_init_script }}"

- name: Enable overlayfs in boot time (upstart)
  command: >
    update-rc.d mount-overlayfs defaults
  when: ansible_lsb.major_release|int < 15

- name: Enable overlayfs in boot time (systemd)
  command: >
    systemctl enable overlayfs.service
  when: ansible_lsb.major_release|int >= 15

- name: Set locale timezone (trusty) 
  copy:
    content: "{{ target_timezone }}"
    dest: "/etc/timezone"
    owner: root
    group: root
    mode: 0644
  when: ansible_lsb.major_release|int < 15

- name: Set locale timezone
  file:
    src: "/usr/share/zoneinfo/{{ target_timezone }}"
    dest: "/etc/localtime"
    state: link
  when: ansible_lsb.major_release|int >= 15

- name: Update timezone
  command: >
    /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
