# =============================================================================
#
# - Copyright (C) 2016     George Li <yongxinl@outlook.com>
#
# - This is part of HomeVault imagebuilder project.
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

---
- name: encrypt password hash for root user
  command: >
    mkpasswd --method=sha-512 {{ target_root_password }}
  register: root_password_hash

- name: update target and set root password
  user:
    name: root
    password: "{{ root_password_hash.stdout }}"

- name: update target and set locale to default profile
  lineinfile:
    dest: "/etc/profile.d/setenv.sh"
    line: "{{ item }}"
    create: yes
    state: present
    mode: 0755
  with_items:
    - "export LC_ALL=C"
    - "export DEBIAN_FRONTEND=noninteractive"
  when: ansible_os_family == "Debian"

- name: update target and setup network interface
  template:
    src: "{{ item.name }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ basefs_configuration }}"
  when: ansible_distribution_release == "trusty"

- name: update target and change network waiting time
  replace:
    dest: "/etc/init/failsafe.conf"
    regexp: "[245][039]$"
    replace: "3"
  when: ansible_distribution_release == "trusty"

- name: update target and change NTP servers pool
  lineinfile:
    dest: "/etc/ntp.conf"
    regexp: "{{ item.regxp }}"
    line: "{{ item.line }}"
    create: yes
    state: present
    mode: 0644
  with_items:
    - { regxp: '^server 0.*', line: 'server 0.au.pool.ntp.org' }
    - { regxp: '^server 1.*', line: 'server 1.au.pool.ntp.org' }
    - { regxp: '^server 2.*', line: 'server 2.au.pool.ntp.org' }
    - { regxp: '^server 3.*', line: 'server 3.au.pool.ntp.org' }

- name: update target and copy init.d script
  template:
    src: "{{ item.name }}"
    dest: "/etc/init.d/{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode|default('0644') }}"
  with_items: "{{ basefs_init_script }}"

- name: update target and add script into booting
  command: >
    update-rc.d {{ item.dest }} defaults
  with_items: "{{ basefs_init_script }}"

- name: update target and set timezone variables
  copy:
    content: "{{ target_timezone }}"
    dest: "/etc/timezone"
    owner: root
    group: root
    mode: 0644

- name: update target and update timezone
  command: >
    /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: copy presistent files to backup storage
  command: rsync -R {{ item }} /tmp/persistent
  with_items: "{{ persistent_files }}"
  when: uninstall_build_kernel == "yes" and persistent_files is defined

- name: create presistent marker in backup storage
  file:
    path: "/tmp/persistent/persistent.stamp"
    state: touch
  when: uninstall_build_kernel == "yes" and persistent_files is defined